export type {
  BaseDomainEvent,
  DomainEvent,
  DomainEventType,
  InquiryConverted,
  InquiryDeclined,
  DealPhaseChanged,
  DealWon,
  DealLost,
  ContractCreated,
  ContractCompleted,
  ContractCancelled,
  InvoicePaid,
  InvoiceOverdue,
  RequestCreated,
  RequestSubmitted,
  RequestApproved,
  RequestRejected,
  RequestRevised,
  RequestResubmitted,
  StepApproved,
  StepRejected,
} from "./types";
export { EventDispatcher, dispatcher } from "./dispatcher";
export type { EventHandler } from "./dispatcher";
